#- type: job
#  id: Student
#  name: job-name-student
#  description: job-description-student
#  playTimeTracker: JobPassenger # (・ω・｀)
#  startingGear: StudentGear
#  setPreference: false
#  canBeAntag: false
#  icon: "Passenger" # TODO
#  supervisors: job-supervisors-teachers

- type: startingGear
  id: StudentGear
  equipment:
#    jumpsuit: ClothingUniformSchoolGakuranBlack #hey we are about 500~ years in the fucking future, why the fuck are we using japanese student uniforms?
    id: StudentIDCard
    shoes: ClothingShoesColorBlack
    back: ClothingBackpack
#  innerclothingskirt: UniformSchoolgirlDusk
  satchel: ClothingBackpackSatchel
  duffelbag: ClothingBackpackDuffel
